---
- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted

- name: Restart k3s
  ansible.builtin.systemd:
    name: k3s
    state: restarted
    daemon_reload: true
  when:
    - ansible_facts.services is not defined or 'k3s.service' in ansible_facts.services
